select * from customer_data

----Q1. What is the total revenue generated by male vs. female customers?
select gender, sum(purchase_amount)  as revenue from customer_data
group by gender
-----Q2. Which customers used a discount but still spent more than the average purchase amount?
select customer_id, purchase_amount
from customer_data where
discount_applied='yes' and  purchase_amount >= (select AVG(purchase_amount) from customer_data)


-- Q3. Which are the top 5 products with the highest average review rating?
  select   item_purchased from customer_data 
where review_rating > (select avg(review_rating) from customer_data )


SELECT item_purchased,
       ROUND(AVG(CAST(review_rating AS FLOAT)), 2) AS average_product_rating
FROM customer_data
GROUP BY item_purchased
ORDER BY AVG(CAST(review_rating AS FLOAT)) DESC
OFFSET 0 ROWS FETCH NEXT 5 ROWS ONLY;


-- Compare the average Purchase Amounts between Standard and Express Shipping. 
select AVG(purchase_amount) AS 'average purchase', shipping_type from customer_data 
where shipping_type IN ('Express','Standard')
GROUP BY shipping_type

----Q5. Do subscribed customers spend more? Compare average spend and total revenue 
--between subscribers and non-subscribers.

select count(customer_id) as " number of customer",sum(purchase_amount) as "total revenue",avg(purchase_amount) as "average purchase",subscription_status
from customer_data
group by subscription_status


--Q6. Which 5 products have the highest percentage of purchases with discounts applied?
SELECT 
  item_purchased, 
  SUM(purchase_amount) AS total_purchase_amount,
  (SUM(purchase_amount) * 100.0) / SUM(SUM(purchase_amount)) OVER () AS percentage_of_total
  
FROM 
  customer_data
WHERE 
  discount_applied = 'yes'
GROUP BY 
  item_purchased
ORDER BY
  total_purchase_amount DESC
OFFSET 0 ROWS FETCH NEXT 5 ROWS ONLY;
--
--Q7. Segment customers into New, Returning, and Loyal based on their total 
-- number of previous purchases, and show the count of each segment. 


WITH customer_type AS (
  SELECT 
    customer_id, 
    previous_purchases,
    CASE 
      WHEN previous_purchases = 1 THEN 'new'
      WHEN previous_purchases BETWEEN 2 AND 10 THEN 'returning'
      ELSE 'loyal'
    END AS customer_segment
  FROM 
    customer_data
)
SELECT 
  customer_segment,
  COUNT(*) AS number_of_customers
FROM 
  customer_type
GROUP BY 
  customer_segment;



  ------------- 
  SELECT item_purchased , sum(purchase_amount) as "purchased amount",category 
from customer_data
group by category ,item_purchased
order by item_purchased  asc 
offset 0 rows fetch next 3 rows only 


--------Q8. What are the top 3 most purchased products within each category?
WITH item_count AS (
  SELECT 
    category,
    item_purchased,
    COUNT(customer_id) AS total_order,
    ROW_NUMBER() OVER (PARTITION BY category ORDER BY COUNT(customer_id) DESC) AS item_rank
  FROM 
    customer_data
  GROUP BY 
    category, item_purchased
)
SELECT 
  category,
  item_purchased,
  total_order
FROM 
  item_count
WHERE 
  item_rank <= 3
ORDER BY
  category, item_rank;

  ---Q9.are customer who repeat buying ( previous purchased is more that 4 ) also likely to subscribe

  select subscription_status  ,count(customer_id ) as " repeat buyer"
  from customer_data 
  where previous_purchases > 5
 group by subscription_status


 -----Q10.what is the revenue contribution of each age goup
 select * from customer_data
 select sum(purchase_amount) as "total_revenue" , age_group
 from customer_data
 group by age_group
 order by total_revenue desc 



 